apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-html
  labels:
    app: static-html
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-html
  template:
    metadata:
      labels:
        app: static-html
    spec:
      containers:
      - name: static-html
        image: bharathg125/demofile:v1
        ports:
        - containerPort: 80
