apiVersion: v1
kind: Service
metadata:
  name: static-html
spec:
  selector:
    app: static-html   # ✅ This matches Deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
