name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/demofile:${{ github.run_id }}

  update-helm-tag:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update Helm values.yaml with new image tag
      run: |
        sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm-chart/values.yaml

    - name: Commit and Push updated Helm values.yaml
      run: |
        git config --global user.email "bharathg1252001@gmail.com"
        git config --global user.name "Bharath1252001"
        git add helm-chart/values.yaml
        git commit -m "Update tag in Helm chart to ${{ github.run_id }} [skip ci]"
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/Bharath1252001/demo.git HEAD:main

  helm-upgrade:
    runs-on: ubuntu-latest
    needs: update-helm-tag

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name demo-cluster

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Helm Upgrade to Ensure Pods Running
      run: |
        helm upgrade demo-app ./helm-chart --install --namespace default
